package com.example.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.stereotype.Component;

import com.example.demo.model.Country;
import com.example.demo.model.Seller;
import com.example.demo.model.MenuItemCategory;
import com.example.demo.model.City;
import com.example.demo.model.RestaurantBrand;
import com.example.demo.model.Restaurant;
import com.example.demo.model.MenuItem;

import com.example.demo.service.CountryService;
import com.example.demo.service.SellerService;
import com.example.demo.service.MenuItemCategoryService;
import com.example.demo.service.CityService;
import com.example.demo.service.RestaurantBrandService;
import com.example.demo.service.RestaurantService;
import com.example.demo.service.MenuItemService;


@SpringBootApplication
public class Application {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
}

@Component
class DemoCommandLineRunner implements CommandLineRunner {
	
	@Autowired
	CountryService countryService;
	@Autowired
	SellerService sellerService;
	@Autowired
	MenuItemCategoryService menuItemCategoryService;
	@Autowired
	CityService cityService;
	@Autowired
	RestaurantBrandService restaurantBrandService;
	@Autowired
	RestaurantService restaurantService;
	@Autowired
	MenuItemService menuItemService;
	
	
	@Override
	public void run(String... arg0) throws Exception {
		
		// Country
		Country country1 = new Country();
		country1.setName("name1");
		countryService.save(country1);
		Country country2 = new Country();
		country2.setName("name2");
		countryService.save(country2);
		// Seller
		Seller seller1 = new Seller();
		seller1.setUsername("username1");
		seller1.setPassword("password1");
		seller1.setFirstName("firstName1");
		seller1.setLastName("lastName1");
		sellerService.save(seller1);
		Seller seller2 = new Seller();
		seller2.setUsername("username2");
		seller2.setPassword("password2");
		seller2.setFirstName("firstName2");
		seller2.setLastName("lastName2");
		sellerService.save(seller2);
		Seller seller3 = new Seller();
		seller3.setUsername("username3");
		seller3.setPassword("password3");
		seller3.setFirstName("firstName3");
		seller3.setLastName("lastName3");
		sellerService.save(seller3);
		Seller seller4 = new Seller();
		seller4.setUsername("username4");
		seller4.setPassword("password4");
		seller4.setFirstName("firstName4");
		seller4.setLastName("lastName4");
		sellerService.save(seller4);
		// MenuItemCategory
		MenuItemCategory menuItemCategory1 = new MenuItemCategory();
		menuItemCategory1.setName("name1");
		menuItemCategoryService.save(menuItemCategory1);
		MenuItemCategory menuItemCategory2 = new MenuItemCategory();
		menuItemCategory2.setName("name2");
		menuItemCategoryService.save(menuItemCategory2);
		MenuItemCategory menuItemCategory3 = new MenuItemCategory();
		menuItemCategory3.setName("name3");
		menuItemCategoryService.save(menuItemCategory3);
		MenuItemCategory menuItemCategory4 = new MenuItemCategory();
		menuItemCategory4.setName("name4");
		menuItemCategoryService.save(menuItemCategory4);
		MenuItemCategory menuItemCategory5 = new MenuItemCategory();
		menuItemCategory5.setName("name5");
		menuItemCategoryService.save(menuItemCategory5);
		MenuItemCategory menuItemCategory6 = new MenuItemCategory();
		menuItemCategory6.setName("name6");
		menuItemCategoryService.save(menuItemCategory6);
		MenuItemCategory menuItemCategory7 = new MenuItemCategory();
		menuItemCategory7.setName("name7");
		menuItemCategoryService.save(menuItemCategory7);
		MenuItemCategory menuItemCategory8 = new MenuItemCategory();
		menuItemCategory8.setName("name8");
		menuItemCategoryService.save(menuItemCategory8);
		// City
		City city1 = new City();
		city1.setName("name1");
		city1.setCountry(country1);
		cityService.save(city1);
		City city2 = new City();
		city2.setName("name2");
		city2.setCountry(country2);				
		cityService.save(city2);
		City city3 = new City();
		city3.setName("name3");
		city3.setCountry(country1);
		cityService.save(city3);
		City city4 = new City();
		city4.setName("name4");
		city4.setCountry(country2);				
		cityService.save(city4);
		City city5 = new City();
		city5.setName("name5");
		city5.setCountry(country1);
		cityService.save(city5);
		City city6 = new City();
		city6.setName("name6");
		city6.setCountry(country2);				
		cityService.save(city6);
		City city7 = new City();
		city7.setName("name7");
		city7.setCountry(country1);
		cityService.save(city7);
		City city8 = new City();
		city8.setName("name8");
		city8.setCountry(country2);				
		cityService.save(city8);
		City city9 = new City();
		city9.setName("name9");
		city9.setCountry(country1);
		cityService.save(city9);
		City city10 = new City();
		city10.setName("name10");
		city10.setCountry(country2);				
		cityService.save(city10);
		City city11 = new City();
		city11.setName("name11");
		city11.setCountry(country1);
		cityService.save(city11);
		City city12 = new City();
		city12.setName("name12");
		city12.setCountry(country2);				
		cityService.save(city12);
		City city13 = new City();
		city13.setName("name13");
		city13.setCountry(country1);
		cityService.save(city13);
		City city14 = new City();
		city14.setName("name14");
		city14.setCountry(country2);				
		cityService.save(city14);
		City city15 = new City();
		city15.setName("name15");
		city15.setCountry(country1);
		cityService.save(city15);
		City city16 = new City();
		city16.setName("name16");
		city16.setCountry(country2);				
		cityService.save(city16);
		// RestaurantBrand
		RestaurantBrand restaurantBrand1 = new RestaurantBrand();
		restaurantBrand1.setName("name1");
		restaurantBrand1.setSeller(seller1);
		restaurantBrandService.save(restaurantBrand1);
		RestaurantBrand restaurantBrand2 = new RestaurantBrand();
		restaurantBrand2.setName("name2");
		restaurantBrand2.setSeller(seller2);				
		restaurantBrandService.save(restaurantBrand2);
		RestaurantBrand restaurantBrand3 = new RestaurantBrand();
		restaurantBrand3.setName("name3");
		restaurantBrand3.setSeller(seller1);
		restaurantBrandService.save(restaurantBrand3);
		RestaurantBrand restaurantBrand4 = new RestaurantBrand();
		restaurantBrand4.setName("name4");
		restaurantBrand4.setSeller(seller2);				
		restaurantBrandService.save(restaurantBrand4);
		RestaurantBrand restaurantBrand5 = new RestaurantBrand();
		restaurantBrand5.setName("name5");
		restaurantBrand5.setSeller(seller1);
		restaurantBrandService.save(restaurantBrand5);
		RestaurantBrand restaurantBrand6 = new RestaurantBrand();
		restaurantBrand6.setName("name6");
		restaurantBrand6.setSeller(seller2);				
		restaurantBrandService.save(restaurantBrand6);
		RestaurantBrand restaurantBrand7 = new RestaurantBrand();
		restaurantBrand7.setName("name7");
		restaurantBrand7.setSeller(seller1);
		restaurantBrandService.save(restaurantBrand7);
		RestaurantBrand restaurantBrand8 = new RestaurantBrand();
		restaurantBrand8.setName("name8");
		restaurantBrand8.setSeller(seller2);				
		restaurantBrandService.save(restaurantBrand8);
		RestaurantBrand restaurantBrand9 = new RestaurantBrand();
		restaurantBrand9.setName("name9");
		restaurantBrand9.setSeller(seller1);
		restaurantBrandService.save(restaurantBrand9);
		RestaurantBrand restaurantBrand10 = new RestaurantBrand();
		restaurantBrand10.setName("name10");
		restaurantBrand10.setSeller(seller2);				
		restaurantBrandService.save(restaurantBrand10);
		RestaurantBrand restaurantBrand11 = new RestaurantBrand();
		restaurantBrand11.setName("name11");
		restaurantBrand11.setSeller(seller1);
		restaurantBrandService.save(restaurantBrand11);
		RestaurantBrand restaurantBrand12 = new RestaurantBrand();
		restaurantBrand12.setName("name12");
		restaurantBrand12.setSeller(seller2);				
		restaurantBrandService.save(restaurantBrand12);
		RestaurantBrand restaurantBrand13 = new RestaurantBrand();
		restaurantBrand13.setName("name13");
		restaurantBrand13.setSeller(seller1);
		restaurantBrandService.save(restaurantBrand13);
		RestaurantBrand restaurantBrand14 = new RestaurantBrand();
		restaurantBrand14.setName("name14");
		restaurantBrand14.setSeller(seller2);				
		restaurantBrandService.save(restaurantBrand14);
		RestaurantBrand restaurantBrand15 = new RestaurantBrand();
		restaurantBrand15.setName("name15");
		restaurantBrand15.setSeller(seller1);
		restaurantBrandService.save(restaurantBrand15);
		RestaurantBrand restaurantBrand16 = new RestaurantBrand();
		restaurantBrand16.setName("name16");
		restaurantBrand16.setSeller(seller2);				
		restaurantBrandService.save(restaurantBrand16);
		RestaurantBrand restaurantBrand17 = new RestaurantBrand();
		restaurantBrand17.setName("name17");
		restaurantBrand17.setSeller(seller1);
		restaurantBrandService.save(restaurantBrand17);
		RestaurantBrand restaurantBrand18 = new RestaurantBrand();
		restaurantBrand18.setName("name18");
		restaurantBrand18.setSeller(seller2);				
		restaurantBrandService.save(restaurantBrand18);
		RestaurantBrand restaurantBrand19 = new RestaurantBrand();
		restaurantBrand19.setName("name19");
		restaurantBrand19.setSeller(seller1);
		restaurantBrandService.save(restaurantBrand19);
		RestaurantBrand restaurantBrand20 = new RestaurantBrand();
		restaurantBrand20.setName("name20");
		restaurantBrand20.setSeller(seller2);				
		restaurantBrandService.save(restaurantBrand20);
		RestaurantBrand restaurantBrand21 = new RestaurantBrand();
		restaurantBrand21.setName("name21");
		restaurantBrand21.setSeller(seller1);
		restaurantBrandService.save(restaurantBrand21);
		RestaurantBrand restaurantBrand22 = new RestaurantBrand();
		restaurantBrand22.setName("name22");
		restaurantBrand22.setSeller(seller2);				
		restaurantBrandService.save(restaurantBrand22);
		RestaurantBrand restaurantBrand23 = new RestaurantBrand();
		restaurantBrand23.setName("name23");
		restaurantBrand23.setSeller(seller1);
		restaurantBrandService.save(restaurantBrand23);
		RestaurantBrand restaurantBrand24 = new RestaurantBrand();
		restaurantBrand24.setName("name24");
		restaurantBrand24.setSeller(seller2);				
		restaurantBrandService.save(restaurantBrand24);
		RestaurantBrand restaurantBrand25 = new RestaurantBrand();
		restaurantBrand25.setName("name25");
		restaurantBrand25.setSeller(seller1);
		restaurantBrandService.save(restaurantBrand25);
		RestaurantBrand restaurantBrand26 = new RestaurantBrand();
		restaurantBrand26.setName("name26");
		restaurantBrand26.setSeller(seller2);				
		restaurantBrandService.save(restaurantBrand26);
		RestaurantBrand restaurantBrand27 = new RestaurantBrand();
		restaurantBrand27.setName("name27");
		restaurantBrand27.setSeller(seller1);
		restaurantBrandService.save(restaurantBrand27);
		RestaurantBrand restaurantBrand28 = new RestaurantBrand();
		restaurantBrand28.setName("name28");
		restaurantBrand28.setSeller(seller2);				
		restaurantBrandService.save(restaurantBrand28);
		RestaurantBrand restaurantBrand29 = new RestaurantBrand();
		restaurantBrand29.setName("name29");
		restaurantBrand29.setSeller(seller1);
		restaurantBrandService.save(restaurantBrand29);
		RestaurantBrand restaurantBrand30 = new RestaurantBrand();
		restaurantBrand30.setName("name30");
		restaurantBrand30.setSeller(seller2);				
		restaurantBrandService.save(restaurantBrand30);
		RestaurantBrand restaurantBrand31 = new RestaurantBrand();
		restaurantBrand31.setName("name31");
		restaurantBrand31.setSeller(seller1);
		restaurantBrandService.save(restaurantBrand31);
		RestaurantBrand restaurantBrand32 = new RestaurantBrand();
		restaurantBrand32.setName("name32");
		restaurantBrand32.setSeller(seller2);				
		restaurantBrandService.save(restaurantBrand32);
		// Restaurant
		Restaurant restaurant1 = new Restaurant();
		restaurant1.setStreetName("streetName1");
		restaurant1.setStreetNumber(10);	
		restaurant1.setGpsLatitude(10.3);		
		restaurant1.setGpsLongitude(10.3);		
		restaurant1.setRestaurantBrand(restaurantBrand1);
		restaurant1.setCity(city1);
		restaurantService.save(restaurant1);
		Restaurant restaurant2 = new Restaurant();
		restaurant2.setStreetName("streetName2");
		restaurant2.setStreetNumber(10);	
		restaurant2.setGpsLatitude(10.3);		
		restaurant2.setGpsLongitude(10.3);		
		restaurant2.setRestaurantBrand(restaurantBrand2);				
		restaurant2.setCity(city2);				
		restaurantService.save(restaurant2);
		Restaurant restaurant3 = new Restaurant();
		restaurant3.setStreetName("streetName3");
		restaurant3.setStreetNumber(10);	
		restaurant3.setGpsLatitude(10.3);		
		restaurant3.setGpsLongitude(10.3);		
		restaurant3.setRestaurantBrand(restaurantBrand1);
		restaurant3.setCity(city1);
		restaurantService.save(restaurant3);
		Restaurant restaurant4 = new Restaurant();
		restaurant4.setStreetName("streetName4");
		restaurant4.setStreetNumber(10);	
		restaurant4.setGpsLatitude(10.3);		
		restaurant4.setGpsLongitude(10.3);		
		restaurant4.setRestaurantBrand(restaurantBrand2);				
		restaurant4.setCity(city2);				
		restaurantService.save(restaurant4);
		Restaurant restaurant5 = new Restaurant();
		restaurant5.setStreetName("streetName5");
		restaurant5.setStreetNumber(10);	
		restaurant5.setGpsLatitude(10.3);		
		restaurant5.setGpsLongitude(10.3);		
		restaurant5.setRestaurantBrand(restaurantBrand1);
		restaurant5.setCity(city1);
		restaurantService.save(restaurant5);
		Restaurant restaurant6 = new Restaurant();
		restaurant6.setStreetName("streetName6");
		restaurant6.setStreetNumber(10);	
		restaurant6.setGpsLatitude(10.3);		
		restaurant6.setGpsLongitude(10.3);		
		restaurant6.setRestaurantBrand(restaurantBrand2);				
		restaurant6.setCity(city2);				
		restaurantService.save(restaurant6);
		Restaurant restaurant7 = new Restaurant();
		restaurant7.setStreetName("streetName7");
		restaurant7.setStreetNumber(10);	
		restaurant7.setGpsLatitude(10.3);		
		restaurant7.setGpsLongitude(10.3);		
		restaurant7.setRestaurantBrand(restaurantBrand1);
		restaurant7.setCity(city1);
		restaurantService.save(restaurant7);
		Restaurant restaurant8 = new Restaurant();
		restaurant8.setStreetName("streetName8");
		restaurant8.setStreetNumber(10);	
		restaurant8.setGpsLatitude(10.3);		
		restaurant8.setGpsLongitude(10.3);		
		restaurant8.setRestaurantBrand(restaurantBrand2);				
		restaurant8.setCity(city2);				
		restaurantService.save(restaurant8);
		Restaurant restaurant9 = new Restaurant();
		restaurant9.setStreetName("streetName9");
		restaurant9.setStreetNumber(10);	
		restaurant9.setGpsLatitude(10.3);		
		restaurant9.setGpsLongitude(10.3);		
		restaurant9.setRestaurantBrand(restaurantBrand1);
		restaurant9.setCity(city1);
		restaurantService.save(restaurant9);
		Restaurant restaurant10 = new Restaurant();
		restaurant10.setStreetName("streetName10");
		restaurant10.setStreetNumber(10);	
		restaurant10.setGpsLatitude(10.3);		
		restaurant10.setGpsLongitude(10.3);		
		restaurant10.setRestaurantBrand(restaurantBrand2);				
		restaurant10.setCity(city2);				
		restaurantService.save(restaurant10);
		Restaurant restaurant11 = new Restaurant();
		restaurant11.setStreetName("streetName11");
		restaurant11.setStreetNumber(10);	
		restaurant11.setGpsLatitude(10.3);		
		restaurant11.setGpsLongitude(10.3);		
		restaurant11.setRestaurantBrand(restaurantBrand1);
		restaurant11.setCity(city1);
		restaurantService.save(restaurant11);
		Restaurant restaurant12 = new Restaurant();
		restaurant12.setStreetName("streetName12");
		restaurant12.setStreetNumber(10);	
		restaurant12.setGpsLatitude(10.3);		
		restaurant12.setGpsLongitude(10.3);		
		restaurant12.setRestaurantBrand(restaurantBrand2);				
		restaurant12.setCity(city2);				
		restaurantService.save(restaurant12);
		Restaurant restaurant13 = new Restaurant();
		restaurant13.setStreetName("streetName13");
		restaurant13.setStreetNumber(10);	
		restaurant13.setGpsLatitude(10.3);		
		restaurant13.setGpsLongitude(10.3);		
		restaurant13.setRestaurantBrand(restaurantBrand1);
		restaurant13.setCity(city1);
		restaurantService.save(restaurant13);
		Restaurant restaurant14 = new Restaurant();
		restaurant14.setStreetName("streetName14");
		restaurant14.setStreetNumber(10);	
		restaurant14.setGpsLatitude(10.3);		
		restaurant14.setGpsLongitude(10.3);		
		restaurant14.setRestaurantBrand(restaurantBrand2);				
		restaurant14.setCity(city2);				
		restaurantService.save(restaurant14);
		Restaurant restaurant15 = new Restaurant();
		restaurant15.setStreetName("streetName15");
		restaurant15.setStreetNumber(10);	
		restaurant15.setGpsLatitude(10.3);		
		restaurant15.setGpsLongitude(10.3);		
		restaurant15.setRestaurantBrand(restaurantBrand1);
		restaurant15.setCity(city1);
		restaurantService.save(restaurant15);
		Restaurant restaurant16 = new Restaurant();
		restaurant16.setStreetName("streetName16");
		restaurant16.setStreetNumber(10);	
		restaurant16.setGpsLatitude(10.3);		
		restaurant16.setGpsLongitude(10.3);		
		restaurant16.setRestaurantBrand(restaurantBrand2);				
		restaurant16.setCity(city2);				
		restaurantService.save(restaurant16);
		Restaurant restaurant17 = new Restaurant();
		restaurant17.setStreetName("streetName17");
		restaurant17.setStreetNumber(10);	
		restaurant17.setGpsLatitude(10.3);		
		restaurant17.setGpsLongitude(10.3);		
		restaurant17.setRestaurantBrand(restaurantBrand1);
		restaurant17.setCity(city1);
		restaurantService.save(restaurant17);
		Restaurant restaurant18 = new Restaurant();
		restaurant18.setStreetName("streetName18");
		restaurant18.setStreetNumber(10);	
		restaurant18.setGpsLatitude(10.3);		
		restaurant18.setGpsLongitude(10.3);		
		restaurant18.setRestaurantBrand(restaurantBrand2);				
		restaurant18.setCity(city2);				
		restaurantService.save(restaurant18);
		Restaurant restaurant19 = new Restaurant();
		restaurant19.setStreetName("streetName19");
		restaurant19.setStreetNumber(10);	
		restaurant19.setGpsLatitude(10.3);		
		restaurant19.setGpsLongitude(10.3);		
		restaurant19.setRestaurantBrand(restaurantBrand1);
		restaurant19.setCity(city1);
		restaurantService.save(restaurant19);
		Restaurant restaurant20 = new Restaurant();
		restaurant20.setStreetName("streetName20");
		restaurant20.setStreetNumber(10);	
		restaurant20.setGpsLatitude(10.3);		
		restaurant20.setGpsLongitude(10.3);		
		restaurant20.setRestaurantBrand(restaurantBrand2);				
		restaurant20.setCity(city2);				
		restaurantService.save(restaurant20);
		Restaurant restaurant21 = new Restaurant();
		restaurant21.setStreetName("streetName21");
		restaurant21.setStreetNumber(10);	
		restaurant21.setGpsLatitude(10.3);		
		restaurant21.setGpsLongitude(10.3);		
		restaurant21.setRestaurantBrand(restaurantBrand1);
		restaurant21.setCity(city1);
		restaurantService.save(restaurant21);
		Restaurant restaurant22 = new Restaurant();
		restaurant22.setStreetName("streetName22");
		restaurant22.setStreetNumber(10);	
		restaurant22.setGpsLatitude(10.3);		
		restaurant22.setGpsLongitude(10.3);		
		restaurant22.setRestaurantBrand(restaurantBrand2);				
		restaurant22.setCity(city2);				
		restaurantService.save(restaurant22);
		Restaurant restaurant23 = new Restaurant();
		restaurant23.setStreetName("streetName23");
		restaurant23.setStreetNumber(10);	
		restaurant23.setGpsLatitude(10.3);		
		restaurant23.setGpsLongitude(10.3);		
		restaurant23.setRestaurantBrand(restaurantBrand1);
		restaurant23.setCity(city1);
		restaurantService.save(restaurant23);
		Restaurant restaurant24 = new Restaurant();
		restaurant24.setStreetName("streetName24");
		restaurant24.setStreetNumber(10);	
		restaurant24.setGpsLatitude(10.3);		
		restaurant24.setGpsLongitude(10.3);		
		restaurant24.setRestaurantBrand(restaurantBrand2);				
		restaurant24.setCity(city2);				
		restaurantService.save(restaurant24);
		Restaurant restaurant25 = new Restaurant();
		restaurant25.setStreetName("streetName25");
		restaurant25.setStreetNumber(10);	
		restaurant25.setGpsLatitude(10.3);		
		restaurant25.setGpsLongitude(10.3);		
		restaurant25.setRestaurantBrand(restaurantBrand1);
		restaurant25.setCity(city1);
		restaurantService.save(restaurant25);
		Restaurant restaurant26 = new Restaurant();
		restaurant26.setStreetName("streetName26");
		restaurant26.setStreetNumber(10);	
		restaurant26.setGpsLatitude(10.3);		
		restaurant26.setGpsLongitude(10.3);		
		restaurant26.setRestaurantBrand(restaurantBrand2);				
		restaurant26.setCity(city2);				
		restaurantService.save(restaurant26);
		Restaurant restaurant27 = new Restaurant();
		restaurant27.setStreetName("streetName27");
		restaurant27.setStreetNumber(10);	
		restaurant27.setGpsLatitude(10.3);		
		restaurant27.setGpsLongitude(10.3);		
		restaurant27.setRestaurantBrand(restaurantBrand1);
		restaurant27.setCity(city1);
		restaurantService.save(restaurant27);
		Restaurant restaurant28 = new Restaurant();
		restaurant28.setStreetName("streetName28");
		restaurant28.setStreetNumber(10);	
		restaurant28.setGpsLatitude(10.3);		
		restaurant28.setGpsLongitude(10.3);		
		restaurant28.setRestaurantBrand(restaurantBrand2);				
		restaurant28.setCity(city2);				
		restaurantService.save(restaurant28);
		Restaurant restaurant29 = new Restaurant();
		restaurant29.setStreetName("streetName29");
		restaurant29.setStreetNumber(10);	
		restaurant29.setGpsLatitude(10.3);		
		restaurant29.setGpsLongitude(10.3);		
		restaurant29.setRestaurantBrand(restaurantBrand1);
		restaurant29.setCity(city1);
		restaurantService.save(restaurant29);
		Restaurant restaurant30 = new Restaurant();
		restaurant30.setStreetName("streetName30");
		restaurant30.setStreetNumber(10);	
		restaurant30.setGpsLatitude(10.3);		
		restaurant30.setGpsLongitude(10.3);		
		restaurant30.setRestaurantBrand(restaurantBrand2);				
		restaurant30.setCity(city2);				
		restaurantService.save(restaurant30);
		Restaurant restaurant31 = new Restaurant();
		restaurant31.setStreetName("streetName31");
		restaurant31.setStreetNumber(10);	
		restaurant31.setGpsLatitude(10.3);		
		restaurant31.setGpsLongitude(10.3);		
		restaurant31.setRestaurantBrand(restaurantBrand1);
		restaurant31.setCity(city1);
		restaurantService.save(restaurant31);
		Restaurant restaurant32 = new Restaurant();
		restaurant32.setStreetName("streetName32");
		restaurant32.setStreetNumber(10);	
		restaurant32.setGpsLatitude(10.3);		
		restaurant32.setGpsLongitude(10.3);		
		restaurant32.setRestaurantBrand(restaurantBrand2);				
		restaurant32.setCity(city2);				
		restaurantService.save(restaurant32);
		Restaurant restaurant33 = new Restaurant();
		restaurant33.setStreetName("streetName33");
		restaurant33.setStreetNumber(10);	
		restaurant33.setGpsLatitude(10.3);		
		restaurant33.setGpsLongitude(10.3);		
		restaurant33.setRestaurantBrand(restaurantBrand1);
		restaurant33.setCity(city1);
		restaurantService.save(restaurant33);
		Restaurant restaurant34 = new Restaurant();
		restaurant34.setStreetName("streetName34");
		restaurant34.setStreetNumber(10);	
		restaurant34.setGpsLatitude(10.3);		
		restaurant34.setGpsLongitude(10.3);		
		restaurant34.setRestaurantBrand(restaurantBrand2);				
		restaurant34.setCity(city2);				
		restaurantService.save(restaurant34);
		Restaurant restaurant35 = new Restaurant();
		restaurant35.setStreetName("streetName35");
		restaurant35.setStreetNumber(10);	
		restaurant35.setGpsLatitude(10.3);		
		restaurant35.setGpsLongitude(10.3);		
		restaurant35.setRestaurantBrand(restaurantBrand1);
		restaurant35.setCity(city1);
		restaurantService.save(restaurant35);
		Restaurant restaurant36 = new Restaurant();
		restaurant36.setStreetName("streetName36");
		restaurant36.setStreetNumber(10);	
		restaurant36.setGpsLatitude(10.3);		
		restaurant36.setGpsLongitude(10.3);		
		restaurant36.setRestaurantBrand(restaurantBrand2);				
		restaurant36.setCity(city2);				
		restaurantService.save(restaurant36);
		Restaurant restaurant37 = new Restaurant();
		restaurant37.setStreetName("streetName37");
		restaurant37.setStreetNumber(10);	
		restaurant37.setGpsLatitude(10.3);		
		restaurant37.setGpsLongitude(10.3);		
		restaurant37.setRestaurantBrand(restaurantBrand1);
		restaurant37.setCity(city1);
		restaurantService.save(restaurant37);
		Restaurant restaurant38 = new Restaurant();
		restaurant38.setStreetName("streetName38");
		restaurant38.setStreetNumber(10);	
		restaurant38.setGpsLatitude(10.3);		
		restaurant38.setGpsLongitude(10.3);		
		restaurant38.setRestaurantBrand(restaurantBrand2);				
		restaurant38.setCity(city2);				
		restaurantService.save(restaurant38);
		Restaurant restaurant39 = new Restaurant();
		restaurant39.setStreetName("streetName39");
		restaurant39.setStreetNumber(10);	
		restaurant39.setGpsLatitude(10.3);		
		restaurant39.setGpsLongitude(10.3);		
		restaurant39.setRestaurantBrand(restaurantBrand1);
		restaurant39.setCity(city1);
		restaurantService.save(restaurant39);
		Restaurant restaurant40 = new Restaurant();
		restaurant40.setStreetName("streetName40");
		restaurant40.setStreetNumber(10);	
		restaurant40.setGpsLatitude(10.3);		
		restaurant40.setGpsLongitude(10.3);		
		restaurant40.setRestaurantBrand(restaurantBrand2);				
		restaurant40.setCity(city2);				
		restaurantService.save(restaurant40);
		Restaurant restaurant41 = new Restaurant();
		restaurant41.setStreetName("streetName41");
		restaurant41.setStreetNumber(10);	
		restaurant41.setGpsLatitude(10.3);		
		restaurant41.setGpsLongitude(10.3);		
		restaurant41.setRestaurantBrand(restaurantBrand1);
		restaurant41.setCity(city1);
		restaurantService.save(restaurant41);
		Restaurant restaurant42 = new Restaurant();
		restaurant42.setStreetName("streetName42");
		restaurant42.setStreetNumber(10);	
		restaurant42.setGpsLatitude(10.3);		
		restaurant42.setGpsLongitude(10.3);		
		restaurant42.setRestaurantBrand(restaurantBrand2);				
		restaurant42.setCity(city2);				
		restaurantService.save(restaurant42);
		Restaurant restaurant43 = new Restaurant();
		restaurant43.setStreetName("streetName43");
		restaurant43.setStreetNumber(10);	
		restaurant43.setGpsLatitude(10.3);		
		restaurant43.setGpsLongitude(10.3);		
		restaurant43.setRestaurantBrand(restaurantBrand1);
		restaurant43.setCity(city1);
		restaurantService.save(restaurant43);
		Restaurant restaurant44 = new Restaurant();
		restaurant44.setStreetName("streetName44");
		restaurant44.setStreetNumber(10);	
		restaurant44.setGpsLatitude(10.3);		
		restaurant44.setGpsLongitude(10.3);		
		restaurant44.setRestaurantBrand(restaurantBrand2);				
		restaurant44.setCity(city2);				
		restaurantService.save(restaurant44);
		Restaurant restaurant45 = new Restaurant();
		restaurant45.setStreetName("streetName45");
		restaurant45.setStreetNumber(10);	
		restaurant45.setGpsLatitude(10.3);		
		restaurant45.setGpsLongitude(10.3);		
		restaurant45.setRestaurantBrand(restaurantBrand1);
		restaurant45.setCity(city1);
		restaurantService.save(restaurant45);
		Restaurant restaurant46 = new Restaurant();
		restaurant46.setStreetName("streetName46");
		restaurant46.setStreetNumber(10);	
		restaurant46.setGpsLatitude(10.3);		
		restaurant46.setGpsLongitude(10.3);		
		restaurant46.setRestaurantBrand(restaurantBrand2);				
		restaurant46.setCity(city2);				
		restaurantService.save(restaurant46);
		Restaurant restaurant47 = new Restaurant();
		restaurant47.setStreetName("streetName47");
		restaurant47.setStreetNumber(10);	
		restaurant47.setGpsLatitude(10.3);		
		restaurant47.setGpsLongitude(10.3);		
		restaurant47.setRestaurantBrand(restaurantBrand1);
		restaurant47.setCity(city1);
		restaurantService.save(restaurant47);
		Restaurant restaurant48 = new Restaurant();
		restaurant48.setStreetName("streetName48");
		restaurant48.setStreetNumber(10);	
		restaurant48.setGpsLatitude(10.3);		
		restaurant48.setGpsLongitude(10.3);		
		restaurant48.setRestaurantBrand(restaurantBrand2);				
		restaurant48.setCity(city2);				
		restaurantService.save(restaurant48);
		Restaurant restaurant49 = new Restaurant();
		restaurant49.setStreetName("streetName49");
		restaurant49.setStreetNumber(10);	
		restaurant49.setGpsLatitude(10.3);		
		restaurant49.setGpsLongitude(10.3);		
		restaurant49.setRestaurantBrand(restaurantBrand1);
		restaurant49.setCity(city1);
		restaurantService.save(restaurant49);
		Restaurant restaurant50 = new Restaurant();
		restaurant50.setStreetName("streetName50");
		restaurant50.setStreetNumber(10);	
		restaurant50.setGpsLatitude(10.3);		
		restaurant50.setGpsLongitude(10.3);		
		restaurant50.setRestaurantBrand(restaurantBrand2);				
		restaurant50.setCity(city2);				
		restaurantService.save(restaurant50);
		Restaurant restaurant51 = new Restaurant();
		restaurant51.setStreetName("streetName51");
		restaurant51.setStreetNumber(10);	
		restaurant51.setGpsLatitude(10.3);		
		restaurant51.setGpsLongitude(10.3);		
		restaurant51.setRestaurantBrand(restaurantBrand1);
		restaurant51.setCity(city1);
		restaurantService.save(restaurant51);
		Restaurant restaurant52 = new Restaurant();
		restaurant52.setStreetName("streetName52");
		restaurant52.setStreetNumber(10);	
		restaurant52.setGpsLatitude(10.3);		
		restaurant52.setGpsLongitude(10.3);		
		restaurant52.setRestaurantBrand(restaurantBrand2);				
		restaurant52.setCity(city2);				
		restaurantService.save(restaurant52);
		Restaurant restaurant53 = new Restaurant();
		restaurant53.setStreetName("streetName53");
		restaurant53.setStreetNumber(10);	
		restaurant53.setGpsLatitude(10.3);		
		restaurant53.setGpsLongitude(10.3);		
		restaurant53.setRestaurantBrand(restaurantBrand1);
		restaurant53.setCity(city1);
		restaurantService.save(restaurant53);
		Restaurant restaurant54 = new Restaurant();
		restaurant54.setStreetName("streetName54");
		restaurant54.setStreetNumber(10);	
		restaurant54.setGpsLatitude(10.3);		
		restaurant54.setGpsLongitude(10.3);		
		restaurant54.setRestaurantBrand(restaurantBrand2);				
		restaurant54.setCity(city2);				
		restaurantService.save(restaurant54);
		Restaurant restaurant55 = new Restaurant();
		restaurant55.setStreetName("streetName55");
		restaurant55.setStreetNumber(10);	
		restaurant55.setGpsLatitude(10.3);		
		restaurant55.setGpsLongitude(10.3);		
		restaurant55.setRestaurantBrand(restaurantBrand1);
		restaurant55.setCity(city1);
		restaurantService.save(restaurant55);
		Restaurant restaurant56 = new Restaurant();
		restaurant56.setStreetName("streetName56");
		restaurant56.setStreetNumber(10);	
		restaurant56.setGpsLatitude(10.3);		
		restaurant56.setGpsLongitude(10.3);		
		restaurant56.setRestaurantBrand(restaurantBrand2);				
		restaurant56.setCity(city2);				
		restaurantService.save(restaurant56);
		Restaurant restaurant57 = new Restaurant();
		restaurant57.setStreetName("streetName57");
		restaurant57.setStreetNumber(10);	
		restaurant57.setGpsLatitude(10.3);		
		restaurant57.setGpsLongitude(10.3);		
		restaurant57.setRestaurantBrand(restaurantBrand1);
		restaurant57.setCity(city1);
		restaurantService.save(restaurant57);
		Restaurant restaurant58 = new Restaurant();
		restaurant58.setStreetName("streetName58");
		restaurant58.setStreetNumber(10);	
		restaurant58.setGpsLatitude(10.3);		
		restaurant58.setGpsLongitude(10.3);		
		restaurant58.setRestaurantBrand(restaurantBrand2);				
		restaurant58.setCity(city2);				
		restaurantService.save(restaurant58);
		Restaurant restaurant59 = new Restaurant();
		restaurant59.setStreetName("streetName59");
		restaurant59.setStreetNumber(10);	
		restaurant59.setGpsLatitude(10.3);		
		restaurant59.setGpsLongitude(10.3);		
		restaurant59.setRestaurantBrand(restaurantBrand1);
		restaurant59.setCity(city1);
		restaurantService.save(restaurant59);
		Restaurant restaurant60 = new Restaurant();
		restaurant60.setStreetName("streetName60");
		restaurant60.setStreetNumber(10);	
		restaurant60.setGpsLatitude(10.3);		
		restaurant60.setGpsLongitude(10.3);		
		restaurant60.setRestaurantBrand(restaurantBrand2);				
		restaurant60.setCity(city2);				
		restaurantService.save(restaurant60);
		Restaurant restaurant61 = new Restaurant();
		restaurant61.setStreetName("streetName61");
		restaurant61.setStreetNumber(10);	
		restaurant61.setGpsLatitude(10.3);		
		restaurant61.setGpsLongitude(10.3);		
		restaurant61.setRestaurantBrand(restaurantBrand1);
		restaurant61.setCity(city1);
		restaurantService.save(restaurant61);
		Restaurant restaurant62 = new Restaurant();
		restaurant62.setStreetName("streetName62");
		restaurant62.setStreetNumber(10);	
		restaurant62.setGpsLatitude(10.3);		
		restaurant62.setGpsLongitude(10.3);		
		restaurant62.setRestaurantBrand(restaurantBrand2);				
		restaurant62.setCity(city2);				
		restaurantService.save(restaurant62);
		Restaurant restaurant63 = new Restaurant();
		restaurant63.setStreetName("streetName63");
		restaurant63.setStreetNumber(10);	
		restaurant63.setGpsLatitude(10.3);		
		restaurant63.setGpsLongitude(10.3);		
		restaurant63.setRestaurantBrand(restaurantBrand1);
		restaurant63.setCity(city1);
		restaurantService.save(restaurant63);
		Restaurant restaurant64 = new Restaurant();
		restaurant64.setStreetName("streetName64");
		restaurant64.setStreetNumber(10);	
		restaurant64.setGpsLatitude(10.3);		
		restaurant64.setGpsLongitude(10.3);		
		restaurant64.setRestaurantBrand(restaurantBrand2);				
		restaurant64.setCity(city2);				
		restaurantService.save(restaurant64);
		// MenuItem
		MenuItem menuItem1 = new MenuItem();
		menuItem1.setName("name1");
		menuItem1.setDescription("description1");
		menuItem1.setPrice(10.3);		
		menuItem1.setMenuItemCategory(menuItemCategory1);
		menuItem1.setRestaurant(restaurant1);
		menuItemService.save(menuItem1);
		MenuItem menuItem2 = new MenuItem();
		menuItem2.setName("name2");
		menuItem2.setDescription("description2");
		menuItem2.setPrice(10.3);		
		menuItem2.setMenuItemCategory(menuItemCategory2);				
		menuItem2.setRestaurant(restaurant2);				
		menuItemService.save(menuItem2);
		MenuItem menuItem3 = new MenuItem();
		menuItem3.setName("name3");
		menuItem3.setDescription("description3");
		menuItem3.setPrice(10.3);		
		menuItem3.setMenuItemCategory(menuItemCategory1);
		menuItem3.setRestaurant(restaurant1);
		menuItemService.save(menuItem3);
		MenuItem menuItem4 = new MenuItem();
		menuItem4.setName("name4");
		menuItem4.setDescription("description4");
		menuItem4.setPrice(10.3);		
		menuItem4.setMenuItemCategory(menuItemCategory2);				
		menuItem4.setRestaurant(restaurant2);				
		menuItemService.save(menuItem4);
		MenuItem menuItem5 = new MenuItem();
		menuItem5.setName("name5");
		menuItem5.setDescription("description5");
		menuItem5.setPrice(10.3);		
		menuItem5.setMenuItemCategory(menuItemCategory1);
		menuItem5.setRestaurant(restaurant1);
		menuItemService.save(menuItem5);
		MenuItem menuItem6 = new MenuItem();
		menuItem6.setName("name6");
		menuItem6.setDescription("description6");
		menuItem6.setPrice(10.3);		
		menuItem6.setMenuItemCategory(menuItemCategory2);				
		menuItem6.setRestaurant(restaurant2);				
		menuItemService.save(menuItem6);
		MenuItem menuItem7 = new MenuItem();
		menuItem7.setName("name7");
		menuItem7.setDescription("description7");
		menuItem7.setPrice(10.3);		
		menuItem7.setMenuItemCategory(menuItemCategory1);
		menuItem7.setRestaurant(restaurant1);
		menuItemService.save(menuItem7);
		MenuItem menuItem8 = new MenuItem();
		menuItem8.setName("name8");
		menuItem8.setDescription("description8");
		menuItem8.setPrice(10.3);		
		menuItem8.setMenuItemCategory(menuItemCategory2);				
		menuItem8.setRestaurant(restaurant2);				
		menuItemService.save(menuItem8);
		MenuItem menuItem9 = new MenuItem();
		menuItem9.setName("name9");
		menuItem9.setDescription("description9");
		menuItem9.setPrice(10.3);		
		menuItem9.setMenuItemCategory(menuItemCategory1);
		menuItem9.setRestaurant(restaurant1);
		menuItemService.save(menuItem9);
		MenuItem menuItem10 = new MenuItem();
		menuItem10.setName("name10");
		menuItem10.setDescription("description10");
		menuItem10.setPrice(10.3);		
		menuItem10.setMenuItemCategory(menuItemCategory2);				
		menuItem10.setRestaurant(restaurant2);				
		menuItemService.save(menuItem10);
		MenuItem menuItem11 = new MenuItem();
		menuItem11.setName("name11");
		menuItem11.setDescription("description11");
		menuItem11.setPrice(10.3);		
		menuItem11.setMenuItemCategory(menuItemCategory1);
		menuItem11.setRestaurant(restaurant1);
		menuItemService.save(menuItem11);
		MenuItem menuItem12 = new MenuItem();
		menuItem12.setName("name12");
		menuItem12.setDescription("description12");
		menuItem12.setPrice(10.3);		
		menuItem12.setMenuItemCategory(menuItemCategory2);				
		menuItem12.setRestaurant(restaurant2);				
		menuItemService.save(menuItem12);
		MenuItem menuItem13 = new MenuItem();
		menuItem13.setName("name13");
		menuItem13.setDescription("description13");
		menuItem13.setPrice(10.3);		
		menuItem13.setMenuItemCategory(menuItemCategory1);
		menuItem13.setRestaurant(restaurant1);
		menuItemService.save(menuItem13);
		MenuItem menuItem14 = new MenuItem();
		menuItem14.setName("name14");
		menuItem14.setDescription("description14");
		menuItem14.setPrice(10.3);		
		menuItem14.setMenuItemCategory(menuItemCategory2);				
		menuItem14.setRestaurant(restaurant2);				
		menuItemService.save(menuItem14);
		MenuItem menuItem15 = new MenuItem();
		menuItem15.setName("name15");
		menuItem15.setDescription("description15");
		menuItem15.setPrice(10.3);		
		menuItem15.setMenuItemCategory(menuItemCategory1);
		menuItem15.setRestaurant(restaurant1);
		menuItemService.save(menuItem15);
		MenuItem menuItem16 = new MenuItem();
		menuItem16.setName("name16");
		menuItem16.setDescription("description16");
		menuItem16.setPrice(10.3);		
		menuItem16.setMenuItemCategory(menuItemCategory2);				
		menuItem16.setRestaurant(restaurant2);				
		menuItemService.save(menuItem16);
		MenuItem menuItem17 = new MenuItem();
		menuItem17.setName("name17");
		menuItem17.setDescription("description17");
		menuItem17.setPrice(10.3);		
		menuItem17.setMenuItemCategory(menuItemCategory1);
		menuItem17.setRestaurant(restaurant1);
		menuItemService.save(menuItem17);
		MenuItem menuItem18 = new MenuItem();
		menuItem18.setName("name18");
		menuItem18.setDescription("description18");
		menuItem18.setPrice(10.3);		
		menuItem18.setMenuItemCategory(menuItemCategory2);				
		menuItem18.setRestaurant(restaurant2);				
		menuItemService.save(menuItem18);
		MenuItem menuItem19 = new MenuItem();
		menuItem19.setName("name19");
		menuItem19.setDescription("description19");
		menuItem19.setPrice(10.3);		
		menuItem19.setMenuItemCategory(menuItemCategory1);
		menuItem19.setRestaurant(restaurant1);
		menuItemService.save(menuItem19);
		MenuItem menuItem20 = new MenuItem();
		menuItem20.setName("name20");
		menuItem20.setDescription("description20");
		menuItem20.setPrice(10.3);		
		menuItem20.setMenuItemCategory(menuItemCategory2);				
		menuItem20.setRestaurant(restaurant2);				
		menuItemService.save(menuItem20);
		MenuItem menuItem21 = new MenuItem();
		menuItem21.setName("name21");
		menuItem21.setDescription("description21");
		menuItem21.setPrice(10.3);		
		menuItem21.setMenuItemCategory(menuItemCategory1);
		menuItem21.setRestaurant(restaurant1);
		menuItemService.save(menuItem21);
		MenuItem menuItem22 = new MenuItem();
		menuItem22.setName("name22");
		menuItem22.setDescription("description22");
		menuItem22.setPrice(10.3);		
		menuItem22.setMenuItemCategory(menuItemCategory2);				
		menuItem22.setRestaurant(restaurant2);				
		menuItemService.save(menuItem22);
		MenuItem menuItem23 = new MenuItem();
		menuItem23.setName("name23");
		menuItem23.setDescription("description23");
		menuItem23.setPrice(10.3);		
		menuItem23.setMenuItemCategory(menuItemCategory1);
		menuItem23.setRestaurant(restaurant1);
		menuItemService.save(menuItem23);
		MenuItem menuItem24 = new MenuItem();
		menuItem24.setName("name24");
		menuItem24.setDescription("description24");
		menuItem24.setPrice(10.3);		
		menuItem24.setMenuItemCategory(menuItemCategory2);				
		menuItem24.setRestaurant(restaurant2);				
		menuItemService.save(menuItem24);
		MenuItem menuItem25 = new MenuItem();
		menuItem25.setName("name25");
		menuItem25.setDescription("description25");
		menuItem25.setPrice(10.3);		
		menuItem25.setMenuItemCategory(menuItemCategory1);
		menuItem25.setRestaurant(restaurant1);
		menuItemService.save(menuItem25);
		MenuItem menuItem26 = new MenuItem();
		menuItem26.setName("name26");
		menuItem26.setDescription("description26");
		menuItem26.setPrice(10.3);		
		menuItem26.setMenuItemCategory(menuItemCategory2);				
		menuItem26.setRestaurant(restaurant2);				
		menuItemService.save(menuItem26);
		MenuItem menuItem27 = new MenuItem();
		menuItem27.setName("name27");
		menuItem27.setDescription("description27");
		menuItem27.setPrice(10.3);		
		menuItem27.setMenuItemCategory(menuItemCategory1);
		menuItem27.setRestaurant(restaurant1);
		menuItemService.save(menuItem27);
		MenuItem menuItem28 = new MenuItem();
		menuItem28.setName("name28");
		menuItem28.setDescription("description28");
		menuItem28.setPrice(10.3);		
		menuItem28.setMenuItemCategory(menuItemCategory2);				
		menuItem28.setRestaurant(restaurant2);				
		menuItemService.save(menuItem28);
		MenuItem menuItem29 = new MenuItem();
		menuItem29.setName("name29");
		menuItem29.setDescription("description29");
		menuItem29.setPrice(10.3);		
		menuItem29.setMenuItemCategory(menuItemCategory1);
		menuItem29.setRestaurant(restaurant1);
		menuItemService.save(menuItem29);
		MenuItem menuItem30 = new MenuItem();
		menuItem30.setName("name30");
		menuItem30.setDescription("description30");
		menuItem30.setPrice(10.3);		
		menuItem30.setMenuItemCategory(menuItemCategory2);				
		menuItem30.setRestaurant(restaurant2);				
		menuItemService.save(menuItem30);
		MenuItem menuItem31 = new MenuItem();
		menuItem31.setName("name31");
		menuItem31.setDescription("description31");
		menuItem31.setPrice(10.3);		
		menuItem31.setMenuItemCategory(menuItemCategory1);
		menuItem31.setRestaurant(restaurant1);
		menuItemService.save(menuItem31);
		MenuItem menuItem32 = new MenuItem();
		menuItem32.setName("name32");
		menuItem32.setDescription("description32");
		menuItem32.setPrice(10.3);		
		menuItem32.setMenuItemCategory(menuItemCategory2);				
		menuItem32.setRestaurant(restaurant2);				
		menuItemService.save(menuItem32);
		MenuItem menuItem33 = new MenuItem();
		menuItem33.setName("name33");
		menuItem33.setDescription("description33");
		menuItem33.setPrice(10.3);		
		menuItem33.setMenuItemCategory(menuItemCategory1);
		menuItem33.setRestaurant(restaurant1);
		menuItemService.save(menuItem33);
		MenuItem menuItem34 = new MenuItem();
		menuItem34.setName("name34");
		menuItem34.setDescription("description34");
		menuItem34.setPrice(10.3);		
		menuItem34.setMenuItemCategory(menuItemCategory2);				
		menuItem34.setRestaurant(restaurant2);				
		menuItemService.save(menuItem34);
		MenuItem menuItem35 = new MenuItem();
		menuItem35.setName("name35");
		menuItem35.setDescription("description35");
		menuItem35.setPrice(10.3);		
		menuItem35.setMenuItemCategory(menuItemCategory1);
		menuItem35.setRestaurant(restaurant1);
		menuItemService.save(menuItem35);
		MenuItem menuItem36 = new MenuItem();
		menuItem36.setName("name36");
		menuItem36.setDescription("description36");
		menuItem36.setPrice(10.3);		
		menuItem36.setMenuItemCategory(menuItemCategory2);				
		menuItem36.setRestaurant(restaurant2);				
		menuItemService.save(menuItem36);
		MenuItem menuItem37 = new MenuItem();
		menuItem37.setName("name37");
		menuItem37.setDescription("description37");
		menuItem37.setPrice(10.3);		
		menuItem37.setMenuItemCategory(menuItemCategory1);
		menuItem37.setRestaurant(restaurant1);
		menuItemService.save(menuItem37);
		MenuItem menuItem38 = new MenuItem();
		menuItem38.setName("name38");
		menuItem38.setDescription("description38");
		menuItem38.setPrice(10.3);		
		menuItem38.setMenuItemCategory(menuItemCategory2);				
		menuItem38.setRestaurant(restaurant2);				
		menuItemService.save(menuItem38);
		MenuItem menuItem39 = new MenuItem();
		menuItem39.setName("name39");
		menuItem39.setDescription("description39");
		menuItem39.setPrice(10.3);		
		menuItem39.setMenuItemCategory(menuItemCategory1);
		menuItem39.setRestaurant(restaurant1);
		menuItemService.save(menuItem39);
		MenuItem menuItem40 = new MenuItem();
		menuItem40.setName("name40");
		menuItem40.setDescription("description40");
		menuItem40.setPrice(10.3);		
		menuItem40.setMenuItemCategory(menuItemCategory2);				
		menuItem40.setRestaurant(restaurant2);				
		menuItemService.save(menuItem40);
		MenuItem menuItem41 = new MenuItem();
		menuItem41.setName("name41");
		menuItem41.setDescription("description41");
		menuItem41.setPrice(10.3);		
		menuItem41.setMenuItemCategory(menuItemCategory1);
		menuItem41.setRestaurant(restaurant1);
		menuItemService.save(menuItem41);
		MenuItem menuItem42 = new MenuItem();
		menuItem42.setName("name42");
		menuItem42.setDescription("description42");
		menuItem42.setPrice(10.3);		
		menuItem42.setMenuItemCategory(menuItemCategory2);				
		menuItem42.setRestaurant(restaurant2);				
		menuItemService.save(menuItem42);
		MenuItem menuItem43 = new MenuItem();
		menuItem43.setName("name43");
		menuItem43.setDescription("description43");
		menuItem43.setPrice(10.3);		
		menuItem43.setMenuItemCategory(menuItemCategory1);
		menuItem43.setRestaurant(restaurant1);
		menuItemService.save(menuItem43);
		MenuItem menuItem44 = new MenuItem();
		menuItem44.setName("name44");
		menuItem44.setDescription("description44");
		menuItem44.setPrice(10.3);		
		menuItem44.setMenuItemCategory(menuItemCategory2);				
		menuItem44.setRestaurant(restaurant2);				
		menuItemService.save(menuItem44);
		MenuItem menuItem45 = new MenuItem();
		menuItem45.setName("name45");
		menuItem45.setDescription("description45");
		menuItem45.setPrice(10.3);		
		menuItem45.setMenuItemCategory(menuItemCategory1);
		menuItem45.setRestaurant(restaurant1);
		menuItemService.save(menuItem45);
		MenuItem menuItem46 = new MenuItem();
		menuItem46.setName("name46");
		menuItem46.setDescription("description46");
		menuItem46.setPrice(10.3);		
		menuItem46.setMenuItemCategory(menuItemCategory2);				
		menuItem46.setRestaurant(restaurant2);				
		menuItemService.save(menuItem46);
		MenuItem menuItem47 = new MenuItem();
		menuItem47.setName("name47");
		menuItem47.setDescription("description47");
		menuItem47.setPrice(10.3);		
		menuItem47.setMenuItemCategory(menuItemCategory1);
		menuItem47.setRestaurant(restaurant1);
		menuItemService.save(menuItem47);
		MenuItem menuItem48 = new MenuItem();
		menuItem48.setName("name48");
		menuItem48.setDescription("description48");
		menuItem48.setPrice(10.3);		
		menuItem48.setMenuItemCategory(menuItemCategory2);				
		menuItem48.setRestaurant(restaurant2);				
		menuItemService.save(menuItem48);
		MenuItem menuItem49 = new MenuItem();
		menuItem49.setName("name49");
		menuItem49.setDescription("description49");
		menuItem49.setPrice(10.3);		
		menuItem49.setMenuItemCategory(menuItemCategory1);
		menuItem49.setRestaurant(restaurant1);
		menuItemService.save(menuItem49);
		MenuItem menuItem50 = new MenuItem();
		menuItem50.setName("name50");
		menuItem50.setDescription("description50");
		menuItem50.setPrice(10.3);		
		menuItem50.setMenuItemCategory(menuItemCategory2);				
		menuItem50.setRestaurant(restaurant2);				
		menuItemService.save(menuItem50);
		MenuItem menuItem51 = new MenuItem();
		menuItem51.setName("name51");
		menuItem51.setDescription("description51");
		menuItem51.setPrice(10.3);		
		menuItem51.setMenuItemCategory(menuItemCategory1);
		menuItem51.setRestaurant(restaurant1);
		menuItemService.save(menuItem51);
		MenuItem menuItem52 = new MenuItem();
		menuItem52.setName("name52");
		menuItem52.setDescription("description52");
		menuItem52.setPrice(10.3);		
		menuItem52.setMenuItemCategory(menuItemCategory2);				
		menuItem52.setRestaurant(restaurant2);				
		menuItemService.save(menuItem52);
		MenuItem menuItem53 = new MenuItem();
		menuItem53.setName("name53");
		menuItem53.setDescription("description53");
		menuItem53.setPrice(10.3);		
		menuItem53.setMenuItemCategory(menuItemCategory1);
		menuItem53.setRestaurant(restaurant1);
		menuItemService.save(menuItem53);
		MenuItem menuItem54 = new MenuItem();
		menuItem54.setName("name54");
		menuItem54.setDescription("description54");
		menuItem54.setPrice(10.3);		
		menuItem54.setMenuItemCategory(menuItemCategory2);				
		menuItem54.setRestaurant(restaurant2);				
		menuItemService.save(menuItem54);
		MenuItem menuItem55 = new MenuItem();
		menuItem55.setName("name55");
		menuItem55.setDescription("description55");
		menuItem55.setPrice(10.3);		
		menuItem55.setMenuItemCategory(menuItemCategory1);
		menuItem55.setRestaurant(restaurant1);
		menuItemService.save(menuItem55);
		MenuItem menuItem56 = new MenuItem();
		menuItem56.setName("name56");
		menuItem56.setDescription("description56");
		menuItem56.setPrice(10.3);		
		menuItem56.setMenuItemCategory(menuItemCategory2);				
		menuItem56.setRestaurant(restaurant2);				
		menuItemService.save(menuItem56);
		MenuItem menuItem57 = new MenuItem();
		menuItem57.setName("name57");
		menuItem57.setDescription("description57");
		menuItem57.setPrice(10.3);		
		menuItem57.setMenuItemCategory(menuItemCategory1);
		menuItem57.setRestaurant(restaurant1);
		menuItemService.save(menuItem57);
		MenuItem menuItem58 = new MenuItem();
		menuItem58.setName("name58");
		menuItem58.setDescription("description58");
		menuItem58.setPrice(10.3);		
		menuItem58.setMenuItemCategory(menuItemCategory2);				
		menuItem58.setRestaurant(restaurant2);				
		menuItemService.save(menuItem58);
		MenuItem menuItem59 = new MenuItem();
		menuItem59.setName("name59");
		menuItem59.setDescription("description59");
		menuItem59.setPrice(10.3);		
		menuItem59.setMenuItemCategory(menuItemCategory1);
		menuItem59.setRestaurant(restaurant1);
		menuItemService.save(menuItem59);
		MenuItem menuItem60 = new MenuItem();
		menuItem60.setName("name60");
		menuItem60.setDescription("description60");
		menuItem60.setPrice(10.3);		
		menuItem60.setMenuItemCategory(menuItemCategory2);				
		menuItem60.setRestaurant(restaurant2);				
		menuItemService.save(menuItem60);
		MenuItem menuItem61 = new MenuItem();
		menuItem61.setName("name61");
		menuItem61.setDescription("description61");
		menuItem61.setPrice(10.3);		
		menuItem61.setMenuItemCategory(menuItemCategory1);
		menuItem61.setRestaurant(restaurant1);
		menuItemService.save(menuItem61);
		MenuItem menuItem62 = new MenuItem();
		menuItem62.setName("name62");
		menuItem62.setDescription("description62");
		menuItem62.setPrice(10.3);		
		menuItem62.setMenuItemCategory(menuItemCategory2);				
		menuItem62.setRestaurant(restaurant2);				
		menuItemService.save(menuItem62);
		MenuItem menuItem63 = new MenuItem();
		menuItem63.setName("name63");
		menuItem63.setDescription("description63");
		menuItem63.setPrice(10.3);		
		menuItem63.setMenuItemCategory(menuItemCategory1);
		menuItem63.setRestaurant(restaurant1);
		menuItemService.save(menuItem63);
		MenuItem menuItem64 = new MenuItem();
		menuItem64.setName("name64");
		menuItem64.setDescription("description64");
		menuItem64.setPrice(10.3);		
		menuItem64.setMenuItemCategory(menuItemCategory2);				
		menuItem64.setRestaurant(restaurant2);				
		menuItemService.save(menuItem64);
		MenuItem menuItem65 = new MenuItem();
		menuItem65.setName("name65");
		menuItem65.setDescription("description65");
		menuItem65.setPrice(10.3);		
		menuItem65.setMenuItemCategory(menuItemCategory1);
		menuItem65.setRestaurant(restaurant1);
		menuItemService.save(menuItem65);
		MenuItem menuItem66 = new MenuItem();
		menuItem66.setName("name66");
		menuItem66.setDescription("description66");
		menuItem66.setPrice(10.3);		
		menuItem66.setMenuItemCategory(menuItemCategory2);				
		menuItem66.setRestaurant(restaurant2);				
		menuItemService.save(menuItem66);
		MenuItem menuItem67 = new MenuItem();
		menuItem67.setName("name67");
		menuItem67.setDescription("description67");
		menuItem67.setPrice(10.3);		
		menuItem67.setMenuItemCategory(menuItemCategory1);
		menuItem67.setRestaurant(restaurant1);
		menuItemService.save(menuItem67);
		MenuItem menuItem68 = new MenuItem();
		menuItem68.setName("name68");
		menuItem68.setDescription("description68");
		menuItem68.setPrice(10.3);		
		menuItem68.setMenuItemCategory(menuItemCategory2);				
		menuItem68.setRestaurant(restaurant2);				
		menuItemService.save(menuItem68);
		MenuItem menuItem69 = new MenuItem();
		menuItem69.setName("name69");
		menuItem69.setDescription("description69");
		menuItem69.setPrice(10.3);		
		menuItem69.setMenuItemCategory(menuItemCategory1);
		menuItem69.setRestaurant(restaurant1);
		menuItemService.save(menuItem69);
		MenuItem menuItem70 = new MenuItem();
		menuItem70.setName("name70");
		menuItem70.setDescription("description70");
		menuItem70.setPrice(10.3);		
		menuItem70.setMenuItemCategory(menuItemCategory2);				
		menuItem70.setRestaurant(restaurant2);				
		menuItemService.save(menuItem70);
		MenuItem menuItem71 = new MenuItem();
		menuItem71.setName("name71");
		menuItem71.setDescription("description71");
		menuItem71.setPrice(10.3);		
		menuItem71.setMenuItemCategory(menuItemCategory1);
		menuItem71.setRestaurant(restaurant1);
		menuItemService.save(menuItem71);
		MenuItem menuItem72 = new MenuItem();
		menuItem72.setName("name72");
		menuItem72.setDescription("description72");
		menuItem72.setPrice(10.3);		
		menuItem72.setMenuItemCategory(menuItemCategory2);				
		menuItem72.setRestaurant(restaurant2);				
		menuItemService.save(menuItem72);
		MenuItem menuItem73 = new MenuItem();
		menuItem73.setName("name73");
		menuItem73.setDescription("description73");
		menuItem73.setPrice(10.3);		
		menuItem73.setMenuItemCategory(menuItemCategory1);
		menuItem73.setRestaurant(restaurant1);
		menuItemService.save(menuItem73);
		MenuItem menuItem74 = new MenuItem();
		menuItem74.setName("name74");
		menuItem74.setDescription("description74");
		menuItem74.setPrice(10.3);		
		menuItem74.setMenuItemCategory(menuItemCategory2);				
		menuItem74.setRestaurant(restaurant2);				
		menuItemService.save(menuItem74);
		MenuItem menuItem75 = new MenuItem();
		menuItem75.setName("name75");
		menuItem75.setDescription("description75");
		menuItem75.setPrice(10.3);		
		menuItem75.setMenuItemCategory(menuItemCategory1);
		menuItem75.setRestaurant(restaurant1);
		menuItemService.save(menuItem75);
		MenuItem menuItem76 = new MenuItem();
		menuItem76.setName("name76");
		menuItem76.setDescription("description76");
		menuItem76.setPrice(10.3);		
		menuItem76.setMenuItemCategory(menuItemCategory2);				
		menuItem76.setRestaurant(restaurant2);				
		menuItemService.save(menuItem76);
		MenuItem menuItem77 = new MenuItem();
		menuItem77.setName("name77");
		menuItem77.setDescription("description77");
		menuItem77.setPrice(10.3);		
		menuItem77.setMenuItemCategory(menuItemCategory1);
		menuItem77.setRestaurant(restaurant1);
		menuItemService.save(menuItem77);
		MenuItem menuItem78 = new MenuItem();
		menuItem78.setName("name78");
		menuItem78.setDescription("description78");
		menuItem78.setPrice(10.3);		
		menuItem78.setMenuItemCategory(menuItemCategory2);				
		menuItem78.setRestaurant(restaurant2);				
		menuItemService.save(menuItem78);
		MenuItem menuItem79 = new MenuItem();
		menuItem79.setName("name79");
		menuItem79.setDescription("description79");
		menuItem79.setPrice(10.3);		
		menuItem79.setMenuItemCategory(menuItemCategory1);
		menuItem79.setRestaurant(restaurant1);
		menuItemService.save(menuItem79);
		MenuItem menuItem80 = new MenuItem();
		menuItem80.setName("name80");
		menuItem80.setDescription("description80");
		menuItem80.setPrice(10.3);		
		menuItem80.setMenuItemCategory(menuItemCategory2);				
		menuItem80.setRestaurant(restaurant2);				
		menuItemService.save(menuItem80);
		MenuItem menuItem81 = new MenuItem();
		menuItem81.setName("name81");
		menuItem81.setDescription("description81");
		menuItem81.setPrice(10.3);		
		menuItem81.setMenuItemCategory(menuItemCategory1);
		menuItem81.setRestaurant(restaurant1);
		menuItemService.save(menuItem81);
		MenuItem menuItem82 = new MenuItem();
		menuItem82.setName("name82");
		menuItem82.setDescription("description82");
		menuItem82.setPrice(10.3);		
		menuItem82.setMenuItemCategory(menuItemCategory2);				
		menuItem82.setRestaurant(restaurant2);				
		menuItemService.save(menuItem82);
		MenuItem menuItem83 = new MenuItem();
		menuItem83.setName("name83");
		menuItem83.setDescription("description83");
		menuItem83.setPrice(10.3);		
		menuItem83.setMenuItemCategory(menuItemCategory1);
		menuItem83.setRestaurant(restaurant1);
		menuItemService.save(menuItem83);
		MenuItem menuItem84 = new MenuItem();
		menuItem84.setName("name84");
		menuItem84.setDescription("description84");
		menuItem84.setPrice(10.3);		
		menuItem84.setMenuItemCategory(menuItemCategory2);				
		menuItem84.setRestaurant(restaurant2);				
		menuItemService.save(menuItem84);
		MenuItem menuItem85 = new MenuItem();
		menuItem85.setName("name85");
		menuItem85.setDescription("description85");
		menuItem85.setPrice(10.3);		
		menuItem85.setMenuItemCategory(menuItemCategory1);
		menuItem85.setRestaurant(restaurant1);
		menuItemService.save(menuItem85);
		MenuItem menuItem86 = new MenuItem();
		menuItem86.setName("name86");
		menuItem86.setDescription("description86");
		menuItem86.setPrice(10.3);		
		menuItem86.setMenuItemCategory(menuItemCategory2);				
		menuItem86.setRestaurant(restaurant2);				
		menuItemService.save(menuItem86);
		MenuItem menuItem87 = new MenuItem();
		menuItem87.setName("name87");
		menuItem87.setDescription("description87");
		menuItem87.setPrice(10.3);		
		menuItem87.setMenuItemCategory(menuItemCategory1);
		menuItem87.setRestaurant(restaurant1);
		menuItemService.save(menuItem87);
		MenuItem menuItem88 = new MenuItem();
		menuItem88.setName("name88");
		menuItem88.setDescription("description88");
		menuItem88.setPrice(10.3);		
		menuItem88.setMenuItemCategory(menuItemCategory2);				
		menuItem88.setRestaurant(restaurant2);				
		menuItemService.save(menuItem88);
		MenuItem menuItem89 = new MenuItem();
		menuItem89.setName("name89");
		menuItem89.setDescription("description89");
		menuItem89.setPrice(10.3);		
		menuItem89.setMenuItemCategory(menuItemCategory1);
		menuItem89.setRestaurant(restaurant1);
		menuItemService.save(menuItem89);
		MenuItem menuItem90 = new MenuItem();
		menuItem90.setName("name90");
		menuItem90.setDescription("description90");
		menuItem90.setPrice(10.3);		
		menuItem90.setMenuItemCategory(menuItemCategory2);				
		menuItem90.setRestaurant(restaurant2);				
		menuItemService.save(menuItem90);
		MenuItem menuItem91 = new MenuItem();
		menuItem91.setName("name91");
		menuItem91.setDescription("description91");
		menuItem91.setPrice(10.3);		
		menuItem91.setMenuItemCategory(menuItemCategory1);
		menuItem91.setRestaurant(restaurant1);
		menuItemService.save(menuItem91);
		MenuItem menuItem92 = new MenuItem();
		menuItem92.setName("name92");
		menuItem92.setDescription("description92");
		menuItem92.setPrice(10.3);		
		menuItem92.setMenuItemCategory(menuItemCategory2);				
		menuItem92.setRestaurant(restaurant2);				
		menuItemService.save(menuItem92);
		MenuItem menuItem93 = new MenuItem();
		menuItem93.setName("name93");
		menuItem93.setDescription("description93");
		menuItem93.setPrice(10.3);		
		menuItem93.setMenuItemCategory(menuItemCategory1);
		menuItem93.setRestaurant(restaurant1);
		menuItemService.save(menuItem93);
		MenuItem menuItem94 = new MenuItem();
		menuItem94.setName("name94");
		menuItem94.setDescription("description94");
		menuItem94.setPrice(10.3);		
		menuItem94.setMenuItemCategory(menuItemCategory2);				
		menuItem94.setRestaurant(restaurant2);				
		menuItemService.save(menuItem94);
		MenuItem menuItem95 = new MenuItem();
		menuItem95.setName("name95");
		menuItem95.setDescription("description95");
		menuItem95.setPrice(10.3);		
		menuItem95.setMenuItemCategory(menuItemCategory1);
		menuItem95.setRestaurant(restaurant1);
		menuItemService.save(menuItem95);
		MenuItem menuItem96 = new MenuItem();
		menuItem96.setName("name96");
		menuItem96.setDescription("description96");
		menuItem96.setPrice(10.3);		
		menuItem96.setMenuItemCategory(menuItemCategory2);				
		menuItem96.setRestaurant(restaurant2);				
		menuItemService.save(menuItem96);
		MenuItem menuItem97 = new MenuItem();
		menuItem97.setName("name97");
		menuItem97.setDescription("description97");
		menuItem97.setPrice(10.3);		
		menuItem97.setMenuItemCategory(menuItemCategory1);
		menuItem97.setRestaurant(restaurant1);
		menuItemService.save(menuItem97);
		MenuItem menuItem98 = new MenuItem();
		menuItem98.setName("name98");
		menuItem98.setDescription("description98");
		menuItem98.setPrice(10.3);		
		menuItem98.setMenuItemCategory(menuItemCategory2);				
		menuItem98.setRestaurant(restaurant2);				
		menuItemService.save(menuItem98);
		MenuItem menuItem99 = new MenuItem();
		menuItem99.setName("name99");
		menuItem99.setDescription("description99");
		menuItem99.setPrice(10.3);		
		menuItem99.setMenuItemCategory(menuItemCategory1);
		menuItem99.setRestaurant(restaurant1);
		menuItemService.save(menuItem99);
		MenuItem menuItem100 = new MenuItem();
		menuItem100.setName("name100");
		menuItem100.setDescription("description100");
		menuItem100.setPrice(10.3);		
		menuItem100.setMenuItemCategory(menuItemCategory2);				
		menuItem100.setRestaurant(restaurant2);				
		menuItemService.save(menuItem100);
		MenuItem menuItem101 = new MenuItem();
		menuItem101.setName("name101");
		menuItem101.setDescription("description101");
		menuItem101.setPrice(10.3);		
		menuItem101.setMenuItemCategory(menuItemCategory1);
		menuItem101.setRestaurant(restaurant1);
		menuItemService.save(menuItem101);
		MenuItem menuItem102 = new MenuItem();
		menuItem102.setName("name102");
		menuItem102.setDescription("description102");
		menuItem102.setPrice(10.3);		
		menuItem102.setMenuItemCategory(menuItemCategory2);				
		menuItem102.setRestaurant(restaurant2);				
		menuItemService.save(menuItem102);
		MenuItem menuItem103 = new MenuItem();
		menuItem103.setName("name103");
		menuItem103.setDescription("description103");
		menuItem103.setPrice(10.3);		
		menuItem103.setMenuItemCategory(menuItemCategory1);
		menuItem103.setRestaurant(restaurant1);
		menuItemService.save(menuItem103);
		MenuItem menuItem104 = new MenuItem();
		menuItem104.setName("name104");
		menuItem104.setDescription("description104");
		menuItem104.setPrice(10.3);		
		menuItem104.setMenuItemCategory(menuItemCategory2);				
		menuItem104.setRestaurant(restaurant2);				
		menuItemService.save(menuItem104);
		MenuItem menuItem105 = new MenuItem();
		menuItem105.setName("name105");
		menuItem105.setDescription("description105");
		menuItem105.setPrice(10.3);		
		menuItem105.setMenuItemCategory(menuItemCategory1);
		menuItem105.setRestaurant(restaurant1);
		menuItemService.save(menuItem105);
		MenuItem menuItem106 = new MenuItem();
		menuItem106.setName("name106");
		menuItem106.setDescription("description106");
		menuItem106.setPrice(10.3);		
		menuItem106.setMenuItemCategory(menuItemCategory2);				
		menuItem106.setRestaurant(restaurant2);				
		menuItemService.save(menuItem106);
		MenuItem menuItem107 = new MenuItem();
		menuItem107.setName("name107");
		menuItem107.setDescription("description107");
		menuItem107.setPrice(10.3);		
		menuItem107.setMenuItemCategory(menuItemCategory1);
		menuItem107.setRestaurant(restaurant1);
		menuItemService.save(menuItem107);
		MenuItem menuItem108 = new MenuItem();
		menuItem108.setName("name108");
		menuItem108.setDescription("description108");
		menuItem108.setPrice(10.3);		
		menuItem108.setMenuItemCategory(menuItemCategory2);				
		menuItem108.setRestaurant(restaurant2);				
		menuItemService.save(menuItem108);
		MenuItem menuItem109 = new MenuItem();
		menuItem109.setName("name109");
		menuItem109.setDescription("description109");
		menuItem109.setPrice(10.3);		
		menuItem109.setMenuItemCategory(menuItemCategory1);
		menuItem109.setRestaurant(restaurant1);
		menuItemService.save(menuItem109);
		MenuItem menuItem110 = new MenuItem();
		menuItem110.setName("name110");
		menuItem110.setDescription("description110");
		menuItem110.setPrice(10.3);		
		menuItem110.setMenuItemCategory(menuItemCategory2);				
		menuItem110.setRestaurant(restaurant2);				
		menuItemService.save(menuItem110);
		MenuItem menuItem111 = new MenuItem();
		menuItem111.setName("name111");
		menuItem111.setDescription("description111");
		menuItem111.setPrice(10.3);		
		menuItem111.setMenuItemCategory(menuItemCategory1);
		menuItem111.setRestaurant(restaurant1);
		menuItemService.save(menuItem111);
		MenuItem menuItem112 = new MenuItem();
		menuItem112.setName("name112");
		menuItem112.setDescription("description112");
		menuItem112.setPrice(10.3);		
		menuItem112.setMenuItemCategory(menuItemCategory2);				
		menuItem112.setRestaurant(restaurant2);				
		menuItemService.save(menuItem112);
		MenuItem menuItem113 = new MenuItem();
		menuItem113.setName("name113");
		menuItem113.setDescription("description113");
		menuItem113.setPrice(10.3);		
		menuItem113.setMenuItemCategory(menuItemCategory1);
		menuItem113.setRestaurant(restaurant1);
		menuItemService.save(menuItem113);
		MenuItem menuItem114 = new MenuItem();
		menuItem114.setName("name114");
		menuItem114.setDescription("description114");
		menuItem114.setPrice(10.3);		
		menuItem114.setMenuItemCategory(menuItemCategory2);				
		menuItem114.setRestaurant(restaurant2);				
		menuItemService.save(menuItem114);
		MenuItem menuItem115 = new MenuItem();
		menuItem115.setName("name115");
		menuItem115.setDescription("description115");
		menuItem115.setPrice(10.3);		
		menuItem115.setMenuItemCategory(menuItemCategory1);
		menuItem115.setRestaurant(restaurant1);
		menuItemService.save(menuItem115);
		MenuItem menuItem116 = new MenuItem();
		menuItem116.setName("name116");
		menuItem116.setDescription("description116");
		menuItem116.setPrice(10.3);		
		menuItem116.setMenuItemCategory(menuItemCategory2);				
		menuItem116.setRestaurant(restaurant2);				
		menuItemService.save(menuItem116);
		MenuItem menuItem117 = new MenuItem();
		menuItem117.setName("name117");
		menuItem117.setDescription("description117");
		menuItem117.setPrice(10.3);		
		menuItem117.setMenuItemCategory(menuItemCategory1);
		menuItem117.setRestaurant(restaurant1);
		menuItemService.save(menuItem117);
		MenuItem menuItem118 = new MenuItem();
		menuItem118.setName("name118");
		menuItem118.setDescription("description118");
		menuItem118.setPrice(10.3);		
		menuItem118.setMenuItemCategory(menuItemCategory2);				
		menuItem118.setRestaurant(restaurant2);				
		menuItemService.save(menuItem118);
		MenuItem menuItem119 = new MenuItem();
		menuItem119.setName("name119");
		menuItem119.setDescription("description119");
		menuItem119.setPrice(10.3);		
		menuItem119.setMenuItemCategory(menuItemCategory1);
		menuItem119.setRestaurant(restaurant1);
		menuItemService.save(menuItem119);
		MenuItem menuItem120 = new MenuItem();
		menuItem120.setName("name120");
		menuItem120.setDescription("description120");
		menuItem120.setPrice(10.3);		
		menuItem120.setMenuItemCategory(menuItemCategory2);				
		menuItem120.setRestaurant(restaurant2);				
		menuItemService.save(menuItem120);
		MenuItem menuItem121 = new MenuItem();
		menuItem121.setName("name121");
		menuItem121.setDescription("description121");
		menuItem121.setPrice(10.3);		
		menuItem121.setMenuItemCategory(menuItemCategory1);
		menuItem121.setRestaurant(restaurant1);
		menuItemService.save(menuItem121);
		MenuItem menuItem122 = new MenuItem();
		menuItem122.setName("name122");
		menuItem122.setDescription("description122");
		menuItem122.setPrice(10.3);		
		menuItem122.setMenuItemCategory(menuItemCategory2);				
		menuItem122.setRestaurant(restaurant2);				
		menuItemService.save(menuItem122);
		MenuItem menuItem123 = new MenuItem();
		menuItem123.setName("name123");
		menuItem123.setDescription("description123");
		menuItem123.setPrice(10.3);		
		menuItem123.setMenuItemCategory(menuItemCategory1);
		menuItem123.setRestaurant(restaurant1);
		menuItemService.save(menuItem123);
		MenuItem menuItem124 = new MenuItem();
		menuItem124.setName("name124");
		menuItem124.setDescription("description124");
		menuItem124.setPrice(10.3);		
		menuItem124.setMenuItemCategory(menuItemCategory2);				
		menuItem124.setRestaurant(restaurant2);				
		menuItemService.save(menuItem124);
		MenuItem menuItem125 = new MenuItem();
		menuItem125.setName("name125");
		menuItem125.setDescription("description125");
		menuItem125.setPrice(10.3);		
		menuItem125.setMenuItemCategory(menuItemCategory1);
		menuItem125.setRestaurant(restaurant1);
		menuItemService.save(menuItem125);
		MenuItem menuItem126 = new MenuItem();
		menuItem126.setName("name126");
		menuItem126.setDescription("description126");
		menuItem126.setPrice(10.3);		
		menuItem126.setMenuItemCategory(menuItemCategory2);				
		menuItem126.setRestaurant(restaurant2);				
		menuItemService.save(menuItem126);
		MenuItem menuItem127 = new MenuItem();
		menuItem127.setName("name127");
		menuItem127.setDescription("description127");
		menuItem127.setPrice(10.3);		
		menuItem127.setMenuItemCategory(menuItemCategory1);
		menuItem127.setRestaurant(restaurant1);
		menuItemService.save(menuItem127);
		MenuItem menuItem128 = new MenuItem();
		menuItem128.setName("name128");
		menuItem128.setDescription("description128");
		menuItem128.setPrice(10.3);		
		menuItem128.setMenuItemCategory(menuItemCategory2);				
		menuItem128.setRestaurant(restaurant2);				
		menuItemService.save(menuItem128);

	}
	
}
